
FROM ros:noetic-ros-base-focal
    
ARG DEBIAN_FRONTEND=noninteractive
ENV CATKIN_WS /workspace

# nvidia-container-runtime
ENV NVIDIA_VISIBLE_DEVICES     ${NVIDIA_VISIBLE_DEVICES:-all}
ENV NVIDIA_DRIVER_CAPABILITIES     ${NVIDIA_DRIVER_CAPABILITIES:+$NVIDIA_DRIVER_CAPABILITIES,}graphics

# APT dependencies
RUN apt update && apt install -y --no-install-recommends    build-essential     git     python3     python3-pip     python-is-python3     libgl1-mesa-glx     libgl1-mesa-dri     ros-noetic-catkin     ros-noetic-rtabmap-ros     ros-noetic-stereo-image-proc     ros-noetic-robot-localization     ros-noetic-camera-info-manager     ros-noetic-ros-numpy     wget     unzip && rm -rf /var/lib/apt/lists/*

RUN mkdir -p ${CATKIN_WS}/src ${CATKIN_WS}/src/dependencies /data /bags

# Install the mapless_mcl_py project
COPY . ${CATKIN_WS}/src/mapless_mcl_ros
WORKDIR ${CATKIN_WS}/src/mapless_mcl_ros/mapless_mcl_py
RUN pip3 install -e . &&     pip3 install -r ${CATKIN_WS}/src/mapless_mcl_ros/mapless_mcl_ros_demos/requirements.txt

# Download the other dependencies
WORKDIR ${CATKIN_WS}/src/dependencies

RUN pip3 install -U catkin-tools

# - Darknet ROS
RUN git clone --recursive https://github.com/leggedrobotics/darknet_ros

# - Split rectify (for running the Carina demo)
# Intermediate tools
# TODO: 'gdown' only for demo
RUN pip3 install -U gdown &&     gdown https://drive.google.com/uc?id=1cig26bATuz5g-EIiUT-YCdjLovWB4RuB &&     unzip split_rectify_stereo.zip &&     rm split_rectify_stereo.zip

# Build all ROS packages
WORKDIR ${CATKIN_WS}

RUN catkin config --extend /opt/ros/noetic && catkin init && catkin build -DCMAKE_BUILD_TYPE=Release
RUN echo 'source "${CATKIN_WS}/devel/setup.bash"' >> ~/.bashrc

# Replace the entrypoint
COPY ./docker/entrypoint.sh /ros_entrypoint.sh
RUN ["chmod", "+x", "/ros_entrypoint.sh"]
